In [1]:
 import pandas as pd

df=pd.read_csv("data.csv")

In [2]:
df

,Actor,Film,Year,Genre,BoxOffice,IMDb
0,Shah Rukh Khan,Tiger Zinda Hai,2023,Action,1050,7.2
1,Salman Khan,Dangal,2016,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Thriller,111,8.3
5,Ayushmann Khurrana,Andhadhun,2018,Horror Comedy,180,7.5
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dul,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri:The Surgical Strike,2019,Action,342,8.2

In [4]:
df["Actor"]

0         Shah Rukh Khan
1            Salman Khan
2             Aamir Khan
3          Ranbir Kapoor
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
9          Kartik Aaryan
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: object

In [8]:
type(df["IMDb"])

pandas.core.series.Series

In [9]:
df[["Actor","Film"]]

                 Actor                     Film
0       Shah Rukh Khan          Tiger Zinda Hai
1          Salman Khan                   Dangal
2           Aamir Khan                   Dangal
3        Ranbir Kapoor               Brahmastra
4        Ranveer Singh                Padmaavat
5   Ayushmann Khurrana                Andhadhun
6        Rajkummar Rao                    Stree
7       Hrithik Roshan                      War
8         Akshay Kumar               Good Newwz
9        Kartik Aaryan          Bhool Bhulaiyaa
10        Varun Dhawan         Badrinath Ki Dul
11       Vicky Kaushal  Uri:The Surgical Strike

In [10]:
df.loc[0]

Actor         Shah Rukh Khan
Film         Tiger Zinda Hai
Year                    2023
Genre                 Action
BoxOffice               1050
IMDb                     7.2
Name: 0, dtype: object

In [11]:
df.loc[5]

Actor        Ayushmann Khurrana
Film                  Andhadhun
Year                       2018
Genre             Horror Comedy
BoxOffice                   180
IMDb                        7.5
Name: 5, dtype: object

In [12]:
df.iloc[0]

Actor         Shah Rukh Khan
Film         Tiger Zinda Hai
Year                    2023
Genre                 Action
BoxOffice               1050
IMDb                     7.2
Name: 0, dtype: object

In [14]:
df.loc[7,"Actor"]

'Hrithik Roshan'

In [15]:
df.iloc[0,1]

'Tiger Zinda Hai'

In [17]:
df.loc[0:2,["Year","Genre"]]

   Year      Genre
0  2023     Action
1  2016     Action
2  2016  Biography

In [19]:
df.at[0,"Actor"]

'Shah Rukh Khan'

In [20]:
df.iat[0,1]

'Tiger Zinda Hai'

In [22]:
df[df["IMDb"]>6]

,Actor,Film,Year,Genre,BoxOffice,IMDb
0,Shah Rukh Khan,Tiger Zinda Hai,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Thriller,111,8.3
5,Ayushmann Khurrana,Andhadhun,2018,Horror Comedy,180,7.5
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dul,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri:The Surgical Strike,2019,Action,342,8.2

In [25]:
df[(df["Year"]>2019)|(df["IMDb"]>9)]

            Actor             Film  Year          Genre  BoxOffice  IMDb
0  Shah Rukh Khan  Tiger Zinda Hai  2023         Action       1050   7.2
3   Ranbir Kapoor       Brahmastra  2022        Fantasy        431   5.6
9   Kartik Aaryan  Bhool Bhulaiyaa  2022  Horror Comedy        266   5.9

In [26]:
df.query("Year > 2015")

,Actor,Film,Year,Genre,BoxOffice,IMDb
0,Shah Rukh Khan,Tiger Zinda Hai,2023,Action,1050,7.2
1,Salman Khan,Dangal,2016,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Thriller,111,8.3
5,Ayushmann Khurrana,Andhadhun,2018,Horror Comedy,180,7.5
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dul,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri:The Surgical Strike,2019,Action,342,8.2