In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("data.csv")

In [3]:
df

,Actor,Film,Year,Genre,BoxOffice,IMDb
0,Shah Rukh Khan,Tiger Zinda Hai,2023,Action,1050,7.2
1,Salman Khan,Dangal,2016,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Thriller,111,8.3
5,Ayushmann Khurrana,Andhadhun,2018,Horror Comedy,180,7.5
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dul,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri:The Surgical Strike,2019,Action,342,8.2

In [12]:
df.sort_values("IMDb",ascending=False)

,Actor,Film,Year,Genre,BoxOffice,IMDb
0,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Ranveer Singh,Padmaavat,2018,Thriller,111,8.3
2,Vicky Kaushal,Uri:The Surgical Strike,2019,Action,342,8.2
3,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
4,Ayushmann Khurrana,Andhadhun,2018,Horror Comedy,180,7.5
5,Shah Rukh Khan,Tiger Zinda Hai,2023,Action,1050,7.2
6,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Varun Dhawan,Badrinath Ki Dul,2017,Romantic Comedy,201,6.1
9,Salman Khan,Dangal,2016,Action,565,6.0
10,Kartik Aaryan,Bhool Bhulaiyaa,2022,Horror Comedy,266,5.9
11,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6

In [13]:
df.reset_index()

,index,Actor,Film,Year,Genre,BoxOffice,IMDb
0,0,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,1,Ranveer Singh,Padmaavat,2018,Thriller,111,8.3
2,2,Vicky Kaushal,Uri:The Surgical Strike,2019,Action,342,8.2
3,3,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
4,4,Ayushmann Khurrana,Andhadhun,2018,Horror Comedy,180,7.5
5,5,Shah Rukh Khan,Tiger Zinda Hai,2023,Action,1050,7.2
6,6,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
7,7,Hrithik Roshan,War,2019,Action,475,6.5
8,8,Varun Dhawan,Badrinath Ki Dul,2017,Romantic Comedy,201,6.1
9,9,Salman Khan,Dangal,2016,Action,565,6.0
10,10,Kartik Aaryan,Bhool Bhulaiyaa,2022,Horror Comedy,266,5.9
11,11,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6

In [14]:
df.reset_index(drop=True, inplace=True)

In [15]:
df

,Actor,Film,Year,Genre,BoxOffice,IMDb
0,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Ranveer Singh,Padmaavat,2018,Thriller,111,8.3
2,Vicky Kaushal,Uri:The Surgical Strike,2019,Action,342,8.2
3,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
4,Ayushmann Khurrana,Andhadhun,2018,Horror Comedy,180,7.5
5,Shah Rukh Khan,Tiger Zinda Hai,2023,Action,1050,7.2
6,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Varun Dhawan,Badrinath Ki Dul,2017,Romantic Comedy,201,6.1
9,Salman Khan,Dangal,2016,Action,565,6.0
10,Kartik Aaryan,Bhool Bhulaiyaa,2022,Horror Comedy,266,5.9
11,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6

In [16]:
df

,Actor,Film,Year,Genre,BoxOffice,IMDb
0,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Ranveer Singh,Padmaavat,2018,Thriller,111,8.3
2,Vicky Kaushal,Uri:The Surgical Strike,2019,Action,342,8.2
3,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
4,Ayushmann Khurrana,Andhadhun,2018,Horror Comedy,180,7.5
5,Shah Rukh Khan,Tiger Zinda Hai,2023,Action,1050,7.2
6,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Varun Dhawan,Badrinath Ki Dul,2017,Romantic Comedy,201,6.1
9,Salman Khan,Dangal,2016,Action,565,6.0
10,Kartik Aaryan,Bhool Bhulaiyaa,2022,Horror Comedy,266,5.9
11,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6

In [17]:
df["Rank"] = df["IMDb"].rank()

In [18]:
df

,Actor,Film,Year,Genre,BoxOffice,IMDb,Rank
0,Aamir Khan,Dangal,2016,Biography,2024,8.4,12.0
1,Ranveer Singh,Padmaavat,2018,Thriller,111,8.3,11.0
2,Vicky Kaushal,Uri:The Surgical Strike,2019,Action,342,8.2,10.0
3,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,8.5
4,Ayushmann Khurrana,Andhadhun,2018,Horror Comedy,180,7.5,8.5
5,Shah Rukh Khan,Tiger Zinda Hai,2023,Action,1050,7.2,7.0
6,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
7,Hrithik Roshan,War,2019,Action,475,6.5,5.0
8,Varun Dhawan,Badrinath Ki Dul,2017,Romantic Comedy,201,6.1,4.0
9,Salman Khan,Dangal,2016,Action,565,6.0,3.0
10,Kartik Aaryan,Bhool Bhulaiyaa,2022,Horror Comedy,266,5.9,2.0
11,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,1.0

In [ ]:
df.rename(columns={"Actor": "Act"}, inplace=True)