In [38]:
import pandas as pd
df=pd.read_csv("data1.csv")

In [39]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [40]:
df.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [41]:
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [42]:
df.dropna()

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [43]:
df.dropna(axis=1)

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [44]:
df.fillna(0)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [45]:
df["Age"].fillna(df["Age"].mean())
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [46]:
df.ffill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [47]:
df.bfill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [48]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [49]:
df.drop_duplicates()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [50]:
df["Name"].str.lower()

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: object

In [51]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [52]:
df["City"].str.contains("delhi", case=False)

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [53]:
df["Email"].str.split("@")

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
3      [charlie, example]
4    [david, example.com]
5       [eve, domain.com]
6    [alice, example.com]
7    [alice, example.com]
8      [charlie, example]
Name: Email, dtype: object

In [54]:

df["Age"] = df["Age"].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [55]:
df["Date"] = pd.to_datetime(df["Date"])

KeyError: 'Date'

In [56]:
df["Age"] = df["Age"].fillna(df["Age"].median()).astype(int)

In [57]:
df["Age"] = df["Age"].astype(int)

In [59]:
type(df["Age"])

pandas.core.series.Series

In [60]:
df["Age Group"] = df["Age"].apply(lambda x: "Adult" if x >= 18 else "Minor")

In [61]:
df

      Name  Age         City Gender              Email   Join Date Age Group
0    Alice   25     New York      F  alice@example.com  01-05-2021     Adult
1  Charlie   25        Delhi      M    charlie@example  20-07-2021     Adult
2      Bob   30  Los Angeles      M    bob@example.com  15-06-2020     Adult
3  Charlie   25        Delhi      M    charlie@example  20-07-2021     Adult
4    David   22       Mumbai      M  david@example.com  12-11-2019     Adult
5      NaN   28        Delhi      F     eve@domain.com         NaN     Adult
6    Alice   25     New York      F  alice@example.com  01-05-2021     Adult
7    Alice   25     New York      F  alice@example.com  01-05-2021     Adult
8  Charlie   25        Delhi      M    charlie@example  20-07-2021     Adult

In [62]:
gender_map = {"M": "Male", "F": "Female"}
df["Gender"] = df["Gender"].map(gender_map)

In [63]:
df

      Name  Age         City  Gender              Email   Join Date Age Group
0    Alice   25     New York  Female  alice@example.com  01-05-2021     Adult
1  Charlie   25        Delhi    Male    charlie@example  20-07-2021     Adult
2      Bob   30  Los Angeles    Male    bob@example.com  15-06-2020     Adult
3  Charlie   25        Delhi    Male    charlie@example  20-07-2021     Adult
4    David   22       Mumbai    Male  david@example.com  12-11-2019     Adult
5      NaN   28        Delhi  Female     eve@domain.com         NaN     Adult
6    Alice   25     New York  Female  alice@example.com  01-05-2021     Adult
7    Alice   25     New York  Female  alice@example.com  01-05-2021     Adult
8  Charlie   25        Delhi    Male    charlie@example  20-07-2021     Adult

In [68]:
df["City"].replace({"Delhi": "New Delhi", "Mum": "Mumbai"})

0       New York
1      New Delhi
2    Los Angeles
3      New Delhi
4         Mumbai
5      New Delhi
6       New York
7       New York
8      New Delhi
Name: City, dtype: object

In [69]:
df

      Name  Age         City  Gender              Email   Join Date Age Group
0    Alice   25     New York  Female  alice@example.com  01-05-2021     Adult
1  Charlie   25        Delhi    Male    charlie@example  20-07-2021     Adult
2      Bob   30  Los Angeles    Male    bob@example.com  15-06-2020     Adult
3  Charlie   25        Delhi    Male    charlie@example  20-07-2021     Adult
4    David   22       Mumbai    Male  david@example.com  12-11-2019     Adult
5      NaN   28        Delhi  Female     eve@domain.com         NaN     Adult
6    Alice   25     New York  Female  alice@example.com  01-05-2021     Adult
7    Alice   25     New York  Female  alice@example.com  01-05-2021     Adult
8  Charlie   25        Delhi    Male    charlie@example  20-07-2021     Adult