In [15]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 78, 92],
    'Science': [90, 82, 89],
    'English': [88, 85, 94]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

      Name  Math  Science  English
0    Alice    85       90       88
1      Bob    78       82       85
2  Charlie    92       89       94

In [17]:
df.melt(id_vars=["Name"],value_vars=["Math","Science","English"],var_name="Subject",value_name="Score")

      Name  Subject  Score
0    Alice     Math     85
1      Bob     Math     78
2  Charlie     Math     92
3    Alice  Science     90
4      Bob  Science     82
5  Charlie  Science     89
6    Alice  English     88
7      Bob  English     85
8  Charlie  English     94

In [18]:
import pandas as pd

data1 = {
    "Name": [
        "Alice", "Alice", "Alice",
        "Bob", "Bob", "Bob",
        "Charlie", "Charlie", "Charlie"
    ],
    "Subject": [
        "Math", "Science", "English",
        "Math", "Science", "English",
        "Math", "Science", "English"
    ],
    "Score": [
        85, 90, 88,
        78, 82, 85,
        92, 89, 94
    ]
}

df = pd.DataFrame(data1)

print(df)

      Name  Subject  Score
0    Alice     Math     85
1    Alice  Science     90
2    Alice  English     88
3      Bob     Math     78
4      Bob  Science     82
5      Bob  English     85
6  Charlie     Math     92
7  Charlie  Science     89
8  Charlie  English     94

In [21]:
df.pivot(index="Name", columns="Subject", values="Score")

Subject  English  Math  Science
Name
Alice         88    85       90
Bob           85    78       82
Charlie       94    92       89

In [23]:
import pandas as pd

data = {
    "Name": [
        "Alice",
        "Alice",
        "Alice",
        "Bob",
        "Bob"
    ],
    "Subject": [
        "Math",
        "Math",
        "Science",
        "Math",
        "Math"
    ],
    "Score": [
        85,
        80,
        90,
        78,
        82
    ]
}

df = pd.DataFrame(data)

print(df)

    Name  Subject  Score
0  Alice     Math     85
1  Alice     Math     80
2  Alice  Science     90
3    Bob     Math     78
4    Bob     Math     82

In [24]:
df.pivot_table(index="Name", columns="Subject", values="Score", aggfunc="mean")

Subject  Math  Science
Name
Alice    82.5     90.0
Bob      80.0      NaN