In [2]:
import pandas as pd
df=pd.read_csv("data.csv")

In [3]:
df

,Actor,Film,Year,Genre,BoxOffice,IMDb
0,Shah Rukh Khan,Tiger Zinda Hai,2023,Action,1050,7.2
1,Salman Khan,Dangal,2016,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Thriller,111,8.3
5,Ayushmann Khurrana,Andhadhun,2018,Horror Comedy,180,7.5
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dul,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri:The Surgical Strike,2019,Action,342,8.2

In [6]:
df=df[df['IMDb']>6.0]

In [7]:
df

,Actor,Film,Year,Genre,BoxOffice,IMDb
0,Shah Rukh Khan,Tiger Zinda Hai,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Thriller,111,8.3
5,Ayushmann Khurrana,Andhadhun,2018,Horror Comedy,180,7.5
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dul,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri:The Surgical Strike,2019,Action,342,8.2

In [9]:
df.to_csv("output.csv",index=False)